.github/release-please-config.json, .github/workflows/create-release-pr.yml
Updated release-please configuration to try and version individual packages
=> chore: update release-please configuration for node packages

packages/OntologyService/__tests__/OntologyService.test.ts, packages/OntologyService/index.ts, packages/OntologyService/jest.config.js, packages/OntologyService/project.json, packages/OntologyService/vite.config.ts, packages/RdfService/__tests__/rdfservice.test.ts, packages/RdfService/index.ts, packages/RdfService/jest.config.js, packages/RdfService/project.json, packages/RdfService/vite.config.ts, scripts/run-packages.sh
Small fixes that where missed in the move from closed to open.
* [update: telicent-io -> telicent-oss](https://github.com/telicent-oss/rdf-libraries/commit/e5f8f0fea0cee4319671c8c2efc8d0f47edbb308)
* Fix tests
=> Small tweaks

.github/workflows/publish-nx-release-candidate.yml
Needed for debugging, can remove after
=> ci(publish-nx-release-candidate.yml):    +workflow_dispatch

.github/workflows/update-docs.yml
Upload api docs as GH pages:
* https://acoolmantelicent.github.io/rdf-libraries/rdf-service/docs/index.html
* https://acoolmantelicent.github.io/rdf-libraries/ontology-service/docs/index.html
- Update ontology-service docs to have correct name
- Update readme
- Add deploy key ([instructions](https://github.com/telicent-oss/rdf-libraries/pull/22#issuecomment-1978750048)) in telicent-oss
=> Ci(update docs.yml)/gh pages

packages/RdfService/package.json
=> update(RdfService package.json): description

.github/workflows/create-release-pr.yml
=> update(create-release-pr.yml): name

packages/OntologyService/package.json
Made consistent with readme
Feels a bit lossy - feel free to make suggestions
=> update(OntologyService package.json): description

.github/workflows/publish-nx.yml
Made consistent to avoid confusion
=> ci(publish-nx.yml): setup-node@v4

README.md, packages/OntologyService/README.md, packages/RdfService/README.md
Regarding: https://github.com/Telicent-io/rdf-libraries/issues/37
Note: Generated docs will NOT appear until a github admin can do: https://github.com/telicent-oss/rdf-libraries/issues/24
=> update(README.md): tweaks

package.json, packages/OntologyService/index.ts, packages/OntologyService/package.json, packages/RdfService/package.json
styles are encoded in a stringified json object
=> fix: decode returned styles

.github/workflows/temp-workflow-publish.yml
https://telicent.atlassian.net/browse/TELFE-126
[Job](https://github.com/telicent-oss/rdf-libraries/actions/runs/9016535868) — **Actually worked** but fails due to [403 version conflict](https://github.com/telicent-oss/rdf-libraries/actions/runs/9016535868/job/24773311860#step:9:41)
=> TELFE-126   update(temp-workflow-publish.yml): Add token

packages/RdfService/index.ts
Issue: https://telicent.atlassian.net/browse/TELFE-144
Adds slash to triplestoreUri in RdfService and therefore OntologyService to allow URLs with or without slashes.
=> TELFE-144 inconsistent ontology service URL format

.github/workflows/publish-dev.yml
=> ci(publish-dev.yml):add dev workflow

README.md
=> fix(README.md): commands

.github/workflows/publish-dev.yml, .github/workflows/publish-nx.yml, .github/workflows/publish-rc.yml, .github/workflows/temp-workflow-publish.yml, .github/workflows/test-release-nx.yml, package.json, pnpm-lock.yaml
Dependabot found a known vulnerability but was unable to fix automatically
=> manually update braces

packages/RdfService/index.ts, packages/RdfService/package.json, pnpm-lock.yaml
unused library with critical vulnerability in it. Removing.
=> fix: remove rdfstore

package.json, packages/OntologyService/package.json, packages/RdfService/package.json
release-please didn't recognise the changes. If release please doesn't recognise this commit I will be able to do a manual publish
=> fix: manually bump version

.github/workflows/publish-dev.yml, .github/workflows/publish-nx.yml, .github/workflows/publish-rc.yml, .github/workflows/temp-workflow-publish.yml, .github/workflows/test-release-nx.yml, packages/OntologyService/package.json, packages/RdfService/package.json
Get all workflows standardised. See if I can trigger a realease automatically
=> feat: update workflows

.github/workflows/create-release-pr.yml, .github/workflows/publish-nx.yml
Signed-off-by: A Coolman <153610820+ACoolmanTelicent@users.noreply.github.com>
=> update: create-release-pr.yml

package-lock.json, package.json, packages/OntologyService/index.ts
Ticket: https://telicent.atlassian.net/browse/TELFE-566
Add getStyles that returns the data in the shape that was accepted pre 0.0.7
I have renamed the `getStyles` to `getAppliedStyles` before re-adding the version that the apps currently expect.
=> Telfe 566/add ds fn

.github/workflows/test-release-nx.yml, packages/RdfService/__tests__/RdfService.test.ts, packages/RdfService/index.ts, packages/RdfService/package.json
I have modified the `runQuery` method to use `POST`.
No new tests have been added and there should be no change of functionlity.
Bumping to rc2.
=> fix: add post request for sparql queries

.gitignore, packages/CatalogService/package.json, packages/OntologyService/package.json, packages/RdfService/package.json, yarn.lock
=> fix: rollup CVE-2024-47068

.github/workflows/publish-nx.yml, .github/workflows/test-release-nx.yml, packages/ontology-find-icon-helper/src/index.ts
- Add build step for ontology-find-icon-helper in `nx-publish`
- Add testing step for ontology-find-icon-helper in `test-release-nx`
This PR is just to publish the new package that @ACoolmanTelicent created as prepatory work for https://telicent.atlassian.net/browse/TELFE-652 https://telicent.atlassian.net/browse/TELFE-653
=> fix(publish-nx): add ontology find icon helper to publish workflow

.github/release-please-config.json, .github/workflows/publish-nx.yml, nx.json, packages/CatalogService/package.json, packages/OntologyService/package.json, packages/RdfService/package.json, packages/ies-service/package.json, packages/ontology-find-icon-helper/README.md, packages/ontology-find-icon-helper/package.json, packages/ontology-find-icon-helper/src/index.test.ts, packages/ontology-find-icon-helper/src/index.ts
Not sure what was wrong with previous version. But just put in a dumb slow version that works.
**Edit**: Oh. The env is per step - not for the entire job. Ok...I'll probably fix that later.
**Edit 2**: Yeh, works https://github.com/telicent-oss/rdf-libraries/actions/runs/12632101500/job/35195119889#step:5:36
=> ci: stability

scripts/lerna/publish:ci.sh
Ticket: 
- Pre-release version: _e.g. v1.2.3-JIRA-123.0_ 
<details>
<summary><strong>Design approval areas</strong></summary>
<hr />
A _indicative_ list of suggested screenshots or videos.
Action each: Mark "`[x]`" (click) for _complete_, or "`[-]`" for _not-applicable_.
</details>
---
<details>
<summary><strong>🕵️ Review Guidance</strong></summary>
---
General guidance
- Generally, approve a PR if it makes the system better, even if it's not perfect. — [Google: The Standard of Code Review](https://google.github.io/eng-practices/review/reviewer/standard.html)
- The aim of both PR AUTHOR and PR REVIEWER is to get the code merged
- Aim for consensus, defined as _everyone can live with the outcome_
- PR with changes requires 2 approvals
- PR with no changes requires 1 approvals
For PR …
=> fix(publish:ci): explain diff
